### ISSUE TITLE
Add iOS 11 Siri Intent extension to FlintDemo and verify Flint works from extension

### ISSUE THREAD

**Issue by marcpalmer** [MontanaFlossCo/Flint#111]

**Comment by AndyDentFree** [comment]
Note that adding Flint to an iMessage extension currently gets the linker warning for FlintCore and ZIPFoundation _Linking against dylib not safe for use in application extension_

**Comment by AndyDentFree** [comment]
With manual setting of General - Deployment Info - App Extensions checkbox "Allow app extension API only" flag is OK - have to do this in both FlintCore and separately for ZIPFoundation

**Comment by marcpalmer** [comment]
@AndyDentFree thanks for reminding me about this. Yeah our stuff should compile fine with that on.

Wondering what to do about ZIPFoundation. I'd like to not have any dependency but copying and pasting the code into Flint seems... harsh. I'd rather have no other dependencies and avoid problems like this.

**Comment by marcpalmer** [comment]
Created #178 for this

**Comment by marcpalmer** [comment]
You know what @AndyDentFree I think we can just cherry pick the parts of ZIPFoundation we need (just creating a zip) and include it directly, along with a credit to the author. It is MIT licenses so I think this is totally safe to do.

**Comment by marcpalmer** [comment]
Duplicate of #110
