### ISSUE TITLE
Change the name of with/using args to make it clear which is input

### ISSUE THREAD

**Issue by marcpalmer** [MontanaFlossCo/Flint#143]
Currently when calling perform(using: presenter, with: input) it is not intuitive which is which.

**Comment by AndyDentFree** [comment]
I did an interesting exercise with OOFILE oooh, about 1992, where I ran a UI-style _focus group_ via email to thrash out these kind of _API Usability_ questions.

Sometimes we found the group highly split on whether something was _obvious_ and had to go for an uglier, but clear, approach.

I'm inclined here to go for trying to emphasise the different nouns, eg: `perform(presenting: presenter, taking: input)`

or more abbreviated:

`perform(ui: presenter, from: input)`

**Comment by marcpalmer** [comment]
Thanks for the excellent feedback @AndyDentFree. I’m inclined to agree

**Comment by marcpalmer** [comment]
I'm planning to go with:

```
MyFeature.amazingThing.perform(input: yourInput)
MyFeature.amazingThing.perform(input: yourInput, presenter: yourPresenter)
MyFeature.amazingThing.perform(presenter: yourPresenter)
MyFeature.amazingThing.perform()
```

Let me know what you think!

**Comment by marcpalmer** [comment]
This should also change the signature of `Action.perform` to `perform(context:,presenter:,completion)`

**Comment by marcpalmer** [comment]
The input type and presenter types are specified by the Action type. As such we must not assume they can be optional. So no I don’t think so. We alteady have this through overloads on StaticActionBinding
