### ISSUE TITLE
Add support for cocoapods

### ISSUE THREAD

**Issue by marcpalmer** [MontanaFlossCo/Flint#146]
We may need to remove the ZIPFoundation dependency to avoid having to cocoapods-ify out workspace however.

**Comment by AAAstorga** [comment]
Any updates on this?

**Comment by marcpalmer** [comment]
Hi @AAAstorga I'm afraid not yet. I will try to look at it this week.

Can you tell me why it is you need Cocoapods support, other than "We already use cocoapods"? Carthage does not affect Cocoapods to my knowledge, so can you confirm that you have been able to use Flint via Carthage with existing Cocoapods projects, and that you just want to have a single dependency solution?
