### ISSUE TITLE
Typo in Shortcuts guide

### ISSUE THREAD

**Issue by Fahrni** [MontanaFlossCo/Flint#325]
**Describe the bug**
There is a repeating "g" in the Shortcuts guide. The text reads **"Showing the system UI for adding or editingg a voice shortcut"**

**To Reproduce**
1. Navigate to https://flint.tools/manual/guides/shortcuts
2. Search for editingg

**Expected behavior**
No double "g"

**Comment by marcpalmer** [comment]
Thanks for that @Fahrni - I'll add a simpler issue template for doc bugs though. TMI!

**Comment by marcpalmer** [comment]
I forgot to mention root case: 2016 MBP keyboard FTW. Not.

**Comment by marcpalmer** [comment]
This fix will appear on the flint.tools site the next time the site content is updated
